"""empty message

Revision ID: d3f375d3a4b9
Revises: 8aee81be9582
Create Date: 2016-03-15 14:13:13.502186

"""

# revision identifiers, used by Alembic.
revision = 'd3f375d3a4b9'
down_revision = '8aee81be9582'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user')
    ### end Alembic commands ###
